### ISSUE TITLE
bisheng-frontend:v0.4.0.dev1 报错有问题，创建和查看助手失败

### ISSUE THREAD

**Issue by xxlest** [dataelement/bisheng#1000]
点击创建助手，后端接口能接收到信息，前端页面报错
错误信息如下：`Unexpected Application Error!
QuestionMarkCircledIcon is not defined
ReferenceError: QuestionMarkCircledIcon is not defined
    at v4e (http://10.0.0.147:3001/assets/index-DKwfKdHu.js:885:25681)
    at Gu (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:30:16998)
    at Oh (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:43963)
    at $h (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:39727)
    at Ty (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:39655)
    at $i (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:39508)
    at nu (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:35875)
    at Dc (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:36678)
    at on (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:30:3274)
    at http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:34207`

docker-compose.yml如下：

`services:
  mysql:
    container_name: bisheng-mysql
    image: mysql:8.0
    
    environment:
      MYSQL_ROOT_PASSWORD: "1234"  # 数据库密码，如果修改需要同步修改bisheng/congfig/config.yaml配置database_url的mysql连接密码
      MYSQL_DATABASE: bisheng
      TZ: Asia/Shanghai
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ${DOCKER_VOLUME_DIRECTORY:-.}/mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -u root -p$$MYSQL_ROOT_PASSWORD"]
      start_period: 30s
      interval: 20s
      timeout: 10s
      retries: 4
    restart: on-failure
    networks:
      - bisheng-network

  redis:
    container_name: bisheng-redis
    image: redis:7.0.4
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data/redis:/data
      - ${DOCKER_VOLUME_DIRECTORY:-.}/redis/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf
    healthcheck:
      test: ["CMD-SHELL", 'redis-cli ping|grep -e "PONG\|NOAUTH"']
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure
    networks:
      - bisheng-network

  office:
    container_name: bisheng-office
    image: onlyoffice/documentserver:7.1.1
    ports:
      - "8701:80"
    environment:
      TZ: Asia/Shanghai
      JWT_ENABLED: false
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/office/bisheng:/var/www/onlyoffice/documentserver/sdkjs-plugins/bisheng
      - ${DOCKER_VOLUME_DIRECTORY:-.}/office/default.json:/etc/onlyoffice/documentserver/default.json
    command: bash -c "supervisorctl restart all"
    restart: on-failure

  backend:
    container_name: bisheng-backend
    image: dataelement/bisheng-backend:v0.4.0.dev1
    ports:
      - "7860:7860"
    environment:
      TZ: Asia/Shanghai
      BS_MILVUS_CONNECTION_ARGS: '{"host":"milvus","port":"19530","user":"","password":"","secure":false}'
      BS_MILVUS_IS_PARTITION: 'true'
      BS_MILVUS_PARTITION_SUFFIX: '1'
      BS_ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      BS_ELASTICSEARCH_SSL_VERIFY: '{}'  # 可根据自己部署的密码进行配置 '{"basic_auth": ("elastic", "elastic")}'
      BS_MINIO_SCHEMA: 'false'
      BS_MINIO_CERT_CHECK: 'false'
      BS_MINIO_ENDPOINT: 'minio:9000'
      BS_MINIO_SHAREPOIN: 'minio:9000'
      BS_MINIO_ACCESS_KEY: 'minioadmin'
      BS_MINIO_SECRET_KEY: 'minioadmin'
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/bisheng/config/config.yaml:/app/bisheng/config.yaml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data/bisheng:/app/data
    security_opt:
      - seccomp:unconfined
    command: bash -c "uvicorn bisheng.main:app --host 0.0.0.0 --port 7860 --no-access-log --workers 2" # --workers 表示使用几个进程，提高并发度
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      start_period: 30s
      interval: 90s
      timeout: 30s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      office:
        condition: service_started
    networks:
      - bisheng-network

  frontend:
    container_name: bisheng-frontend
    image: dataelement/bisheng-frontend:v0.4.0.dev1
    ports:
      - "3001:3001"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DOCKER_VOLUME_DIRECTORY:-.}/nginx/conf.d:/etc/nginx/conf.d
    restart: on-failure
    depends_on:
      - backend
    networks:
      - bisheng-network

  elasticsearch:
    container_name: bisheng-es
    image: docker.io/bitnami/elasticsearch:8.12.0
    user: root
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data/es:/bitnami/elasticsearch/data
    restart: on-failure
    networks:
      - bisheng-network

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: "1000"
      ETCD_QUOTA_BACKEND_BYTES: "4294967296"
      ETCD_SNAPSHOT_COUNT: "50000"
      TZ: Asia/Shanghai
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data/milvus-etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    restart: on-failure
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - bisheng-network

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data/milvus-minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - bisheng-network
    networks:
      - bisheng-network
      
  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.3
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data/milvus:/var/lib/milvus
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      start_period: 90s
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio
    networks:
      - bisheng-network

networks:
  bisheng-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
`

**Comment by xxlest** [comment]
v0.4.0.dev1 工作流编辑报告模板组件也是弹出响应的错误

**Comment by de1icate** [comment]
> 点击创建助手，后端接口能接收到信息，前端页面报错 错误信息如下：`Unexpected Application Error! QuestionMarkCircledIcon is not defined ReferenceError: QuestionMarkCircledIcon is not defined at v4e (http://10.0.0.147:3001/assets/index-DKwfKdHu.js:885:25681) at Gu (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:30:16998) at Oh (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:43963) at $h (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:39727) at Ty (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:39655) at $i (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:39508) at nu (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:35875) at Dc (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:36678) at on (http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:30:3274) at http://10.0.0.147:3001/assets/reactflow-B2QGIWOW.js:32:34207`
> 
> docker-compose.yml如下：
> 
> `services: mysql: container_name: bisheng-mysql image: mysql:8.0
> 
> ```
> environment:
>   MYSQL_ROOT_PASSWORD: "1234"  # 数据库密码，如果修改需要同步修改bisheng/congfig/config.yaml配置database_url的mysql连接密码
>   MYSQL_DATABASE: bisheng
>   TZ: Asia/Shanghai
> volumes:
>   - ${DOCKER_VOLUME_DIRECTORY:-.}/mysql/conf/my.cnf:/etc/mysql/my.cnf
>   - ${DOCKER_VOLUME_DIRECTORY:-.}/mysql/data:/var/lib/mysql
> healthcheck:
>   test: ["CMD-SHELL", "exit | mysql -u root -p$$MYSQL_ROOT_PASSWORD"]
>   start_period: 30s
>   interval: 20s
>   timeout: 10s
>   retries: 4
> restart: on-failure
> networks:
>   - bisheng-network
> ```
> 
> redis: container_name: bisheng-redis image: redis:7.0.4 environment: TZ: Asia/Shanghai volumes: - ${DOCKER_VOLUME_DIRECTORY:-.}/data/redis:/data - ${DOCKER_VOLUME_DIRECTORY:-.}/redis/redis.conf:/etc/redis.conf command: redis-server /etc/redis.conf healthcheck: test: ["CMD-SHELL", 'redis-cli ping|grep -e "PONG|NOAUTH"'] interval: 10s timeout: 5s retries: 3 restart: on-failure networks: - bisheng-network
> 
> office: container_name: bisheng-office image: onlyoffice/documentserver:7.1.1 ports: - "8701:80" environment: TZ: Asia/Shanghai JWT_ENABLED: false volumes: - ${DOCKER_VOLUME_DIRECTORY:-.}/office/bisheng:/var/www/onlyoffice/documentserver/sdkjs-plugins/bisheng - ${DOCKER_VOLUME_DIRECTORY:-.}/office/default.json:/etc/onlyoffice/documentserver/default.json command: bash -c "supervisorctl restart all" restart: on-failure
> 
> backend: container_name: bisheng-backend image: dataelement/bisheng-backend:v0.4.0.dev1 ports: - "7860:7860" environment: TZ: Asia/Shanghai BS_MILVUS_CONNECTION_ARGS: '{"host":"milvus","port":"19530","user":"","password":"","secure":false}' BS_MILVUS_IS_PARTITION: 'true' BS_MILVUS_PARTITION_SUFFIX: '1' BS_ELASTICSEARCH_URL: 'http://elasticsearch:9200' BS_ELASTICSEARCH_SSL_VERIFY: '{}' # 可根据自己部署的密码进行配置 '{"basic_auth": ("elastic", "elastic")}' BS_MINIO_SCHEMA: 'false' BS_MINIO_CERT_CHECK: 'false' BS_MINIO_ENDPOINT: 'minio:9000' BS_MINIO_SHAREPOIN: 'minio:9000' BS_MINIO_ACCESS_KEY: 'minioadmin' BS_MINIO_SECRET_KEY: 'minioadmin' volumes: - ${DOCKER_VOLUME_DIRECTORY:-.}/bisheng/config/config.yaml:/app/bisheng/config.yaml - ${DOCKER_VOLUME_DIRECTORY:-.}/data/bisheng:/app/data security_opt: - seccomp:unconfined command: bash -c "uvicorn bisheng.main:app --host 0.0.0.0 --port 7860 --no-access-log --workers 2" # --workers 表示使用几个进程，提高并发度 restart: on-failure healthcheck: test: ["CMD", "curl", "-f", "http://localhost:7860/health"] start_period: 30s interval: 90s timeout: 30s retries: 3 depends_on: mysql: condition: service_healthy redis: condition: service_healthy office: condition: service_started networks: - bisheng-network
> 
> frontend: container_name: bisheng-frontend image: dataelement/bisheng-frontend:v0.4.0.dev1 ports: - "3001:3001" environment: TZ: Asia/Shanghai volumes: - ${DOCKER_VOLUME_DIRECTORY:-.}/nginx/nginx.conf:/etc/nginx/nginx.conf - ${DOCKER_VOLUME_DIRECTORY:-.}/nginx/conf.d:/etc/nginx/conf.d restart: on-failure depends_on: - backend networks: - bisheng-network
> 
> elasticsearch: container_name: bisheng-es image: docker.io/bitnami/elasticsearch:8.12.0 user: root ports: - "9200:9200" - "9300:9300" environment: TZ: Asia/Shanghai volumes: - ${DOCKER_VOLUME_DIRECTORY:-.}/data/es:/bitnami/elasticsearch/data restart: on-failure networks: - bisheng-network
> 
> etcd: container_name: milvus-etcd image: quay.io/coreos/etcd:v3.5.5 environment: ETCD_AUTO_COMPACTION_MODE: revision ETCD_AUTO_COMPACTION_RETENTION: "1000" ETCD_QUOTA_BACKEND_BYTES: "4294967296" ETCD_SNAPSHOT_COUNT: "50000" TZ: Asia/Shanghai volumes: - ${DOCKER_VOLUME_DIRECTORY:-.}/data/milvus-etcd:/etcd command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd restart: on-failure healthcheck: test: ["CMD", "etcdctl", "endpoint", "health"] interval: 30s timeout: 20s retries: 3 networks: - bisheng-network
> 
> minio: container_name: milvus-minio image: minio/minio:RELEASE.2023-03-20T20-16-18Z environment: MINIO_ACCESS_KEY: minioadmin MINIO_SECRET_KEY: minioadmin ports: - "9100:9000" - "9101:9001" volumes: - /etc/localtime:/etc/localtime:ro - ${DOCKER_VOLUME_DIRECTORY:-.}/data/milvus-minio:/minio_data command: minio server /minio_data --console-address ":9001" restart: on-failure healthcheck: test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"] interval: 30s timeout: 20s retries: 3 networks: - bisheng-network networks: - bisheng-network
> 
> milvus: container_name: milvus-standalone image: milvusdb/milvus:v2.3.3 command: ["milvus", "run", "standalone"] security_opt: - seccomp:unconfined environment: ETCD_ENDPOINTS: etcd:2379 MINIO_ADDRESS: minio:9000 volumes: - /etc/localtime:/etc/localtime:ro - ${DOCKER_VOLUME_DIRECTORY:-.}/data/milvus:/var/lib/milvus restart: on-failure healthcheck: test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"] start_period: 90s interval: 30s timeout: 20s retries: 3 ports: - "19530:19530" - "9091:9091" depends_on: - etcd - minio networks: - bisheng-network
> 
> networks: bisheng-network: driver: bridge ipam: driver: default config: - subnet: 192.168.1.0/24 `

您好，Feat/0.4.0.dev2 (#1003) 本地用docker部署启动，在新建助手打开时也遇到了同样的问题，报错如下：
Unexpected Application Error!
Can't find variable: QuestionMarkCircledIcon
v4e@http://127.0.0.1:3001/assets/index-DKwfKdHu.js:885:25704
Gu@http://127.0.0.1:3001/assets/reactflow-B2QGIWOW.js:30:16999
Oh@http://127.0.0.1:3001/assets/reactflow-B2QGIWOW.js:32:43965
$h@http://127.0.0.1:3001/assets/reactflow-B2QGIWOW.js:32:39729
Ty@http://127.0.0.1:3001/assets/reactflow-B2QGIWOW.js:32:39657
$i@http://127.0.0.1:3001/assets/reactflow-B2QGIWOW.js:32:39510
nu@http://127.0.0.1:3001/assets/reactflow-B2QGIWOW.js:32:35877
Dc@http://127.0.0.1:3001/assets/reactflow-B2QGIWOW.js:32:36680
on@http://127.0.0.1:3001/assets/reactflow-B2QGIWOW.js:30:3275
@http://127.0.0.1:3001/assets/reactflow-B2QGIWOW.js:32:34209

**Comment by dingziyang2022** [comment]
大佬们，有解决办法没？一样的问题
