### ISSUE TITLE
新版使用docker安装后backend启动报错

### ISSUE THREAD

**Issue by Minamiyama** [dataelement/bisheng#117]
日志如下：
<details><summary>Details</summary>
<p>

2023-10-31 12:57:20 [04:57:20] INFO     [04:57:20] - INFO - Logger set up with log      logger.py:28
2023-10-31 12:57:20                     level: 10(DEBUG)                                            
2023-10-31 12:57:20 [04:57:20] INFO     [04:57:20] - INFO - Logger set up with log      logger.py:28
2023-10-31 12:57:20                     level: 10(DEBUG)                                            
2023-10-31 12:57:20            INFO     [04:57:20] - INFO - Log file: data/bisheng.log  logger.py:30
2023-10-31 12:57:20            INFO     [04:57:20] - INFO - Log file: data/bisheng.log  logger.py:30
2023-10-31 12:57:15 INFO:     Stopping parent process [1]
2023-10-31 12:57:16 INFO:     Uvicorn running on http://0.0.0.0:7860 (Press CTRL+C to quit)
2023-10-31 12:57:16 INFO:     Started parent process [1]
2023-10-31 12:57:30 INFO:     Started server process [8]
2023-10-31 12:57:30 INFO:     Waiting for application startup.
2023-10-31 12:57:30 INFO:     Started server process [9]
2023-10-31 12:57:30 INFO:     Waiting for application startup.
2023-10-31 12:57:30 ERROR:    Traceback (most recent call last):
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
2023-10-31 12:57:30     self.dialect.do_execute(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2023-10-31 12:57:30     cursor.execute(statement, parameters)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 163, in execute
2023-10-31 12:57:30     result = self._query(query)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 321, in _query
2023-10-31 12:57:30     conn.query(q)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 505, in query
2023-10-31 12:57:30 [04:57:30] DEBUG    [04:57:30] - DEBUG - Creating database and tables base.py:21
2023-10-31 12:57:30 [04:57:30] DEBUG    [04:57:30] - DEBUG - Creating database and tables base.py:21
2023-10-31 12:57:30            DEBUG    [04:57:30] - DEBUG - Database and tables created  base.py:38
2023-10-31 12:57:30                     successfully                                                
2023-10-31 12:57:30            DEBUG    [04:57:30] - DEBUG - Database and tables created  base.py:38
2023-10-31 12:57:30                     successfully                                                
2023-10-31 12:57:30     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 724, in _read_query_result
2023-10-31 12:57:30     result.read()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1069, in read
2023-10-31 12:57:30     first_packet = self.connection._read_packet()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 676, in _read_packet
2023-10-31 12:57:30     packet.raise_for_error()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 223, in raise_for_error
2023-10-31 12:57:30     err.raise_mysql_exception(self._data)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
2023-10-31 12:57:30     raise errorclass(errno, errval)
2023-10-31 12:57:30 pymysql.err.DataError: (1406, "Data too long for column 'value' at row 1")
2023-10-31 12:57:30 
2023-10-31 12:57:30 The above exception was the direct cause of the following exception:
2023-10-31 12:57:30 
2023-10-31 12:57:30 Traceback (most recent call last):
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
2023-10-31 12:57:30     async with self.lifespan_context(app) as maybe_state:
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
2023-10-31 12:57:30     await self._router.startup()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 656, in startup
2023-10-31 12:57:30     handler()
2023-10-31 12:57:30   File "/app/bisheng/database/base.py", line 79, in create_db_and_tables
2023-10-31 12:57:30     session.commit()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
2023-10-31 12:57:30     self._transaction.commit(_to_root=self.future)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 829, in commit
2023-10-31 12:57:30     self._prepare_impl()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
2023-10-31 12:57:30     self.session.flush()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
2023-10-31 12:57:30     self._flush(objects)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3525, in _flush
2023-10-31 12:57:30     with util.safe_reraise():
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
2023-10-31 12:57:30     compat.raise_(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
2023-10-31 12:57:30     raise exception
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
2023-10-31 12:57:30     flush_context.execute()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
2023-10-31 12:57:30     rec.execute(self)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
2023-10-31 12:57:30     util.preloaded.orm_persistence.save_obj(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
2023-10-31 12:57:30     _emit_insert_statements(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
2023-10-31 12:57:30     result = connection._execute_20(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
2023-10-31 12:57:30     return meth(self, args_10style, kwargs_10style, execution_options)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
2023-10-31 12:57:30     return connection._execute_clauseelement(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
2023-10-31 12:57:30     ret = self._execute_context(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
2023-10-31 12:57:30     self._handle_dbapi_exception(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
2023-10-31 12:57:30     util.raise_(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
2023-10-31 12:57:30     raise exception
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
2023-10-31 12:57:30     self.dialect.do_execute(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2023-10-31 12:57:30     cursor.execute(statement, parameters)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 163, in execute
2023-10-31 12:57:30     result = self._query(query)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 321, in _query
2023-10-31 12:57:30     conn.query(q)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 505, in query
2023-10-31 12:57:30     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 724, in _read_query_result
2023-10-31 12:57:30     result.read()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1069, in read
2023-10-31 12:57:30     first_packet = self.connection._read_packet()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 676, in _read_packet
2023-10-31 12:57:30     packet.raise_for_error()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 223, in raise_for_error
2023-10-31 12:57:30     err.raise_mysql_exception(self._data)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
2023-10-31 12:57:30     raise errorclass(errno, errval)
2023-10-31 12:57:30 sqlalchemy.exc.DataError: (pymysql.err.DataError) (1406, "Data too long for column 'value' at row 1")
2023-10-31 12:57:30 [SQL: INSERT INTO config (value, `key`, comment) VALUES (%(value)s, %(key)s, %(comment)s)]
2023-10-31 12:57:30 [parameters: {'value': '  unstructured_api_url: ""  # 毕昇非结构化数据解析服务地址，提供包括OCR文字识别、表格识别、版式分析等能力。非必填，填写后能够提升PDF、图片、\n  embeddings: # 配置知识库的embedding服务，以下示例填写了两类embedding服务的配置方法 ... (875 characters truncated) ...  # 如果要支持溯源功能，由于溯源会展示源文件，必须配置 oss 存储\n    MINIO_ENDPOINT: ""\n    MINIO_SHAREPOIN: ""\n    MINIO_ACCESS_KEY: ""\n    MINIO_SECRET_KEY: ""\n\n# 全局配置大模型', 'key': 'knowledges', 'comment': None}]
2023-10-31 12:57:30 (Background on this error at: https://sqlalche.me/e/14/9h9h)
2023-10-31 12:57:30 
2023-10-31 12:57:30 ERROR:    Traceback (most recent call last):
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
2023-10-31 12:57:30     self.dialect.do_execute(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2023-10-31 12:57:30     cursor.execute(statement, parameters)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 163, in execute
2023-10-31 12:57:30     result = self._query(query)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 321, in _query
2023-10-31 12:57:30     conn.query(q)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 505, in query
2023-10-31 12:57:30     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 724, in _read_query_result
2023-10-31 12:57:30     result.read()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1069, in read
2023-10-31 12:57:30     first_packet = self.connection._read_packet()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 676, in _read_packet
2023-10-31 12:57:30     packet.raise_for_error()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 223, in raise_for_error
2023-10-31 12:57:30     err.raise_mysql_exception(self._data)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
2023-10-31 12:57:30     raise errorclass(errno, errval)
2023-10-31 12:57:30 pymysql.err.DataError: (1406, "Data too long for column 'value' at row 1")
2023-10-31 12:57:30 
2023-10-31 12:57:30 The above exception was the direct cause of the following exception:
2023-10-31 12:57:30 
2023-10-31 12:57:30 Traceback (most recent call last):
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
2023-10-31 12:57:30     async with self.lifespan_context(app) as maybe_state:
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
2023-10-31 12:57:30     await self._router.startup()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 656, in startup
2023-10-31 12:57:30     handler()
2023-10-31 12:57:30   File "/app/bisheng/database/base.py", line 79, in create_db_and_tables
2023-10-31 12:57:30     session.commit()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
2023-10-31 12:57:30     self._transaction.commit(_to_root=self.future)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 829, in commit
2023-10-31 12:57:30     self._prepare_impl()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
2023-10-31 12:57:30     self.session.flush()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
2023-10-31 12:57:30     self._flush(objects)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3525, in _flush
2023-10-31 12:57:30     with util.safe_reraise():
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
2023-10-31 12:57:30     compat.raise_(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
2023-10-31 12:57:30     raise exception
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
2023-10-31 12:57:30     flush_context.execute()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
2023-10-31 12:57:30     rec.execute(self)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
2023-10-31 12:57:30     util.preloaded.orm_persistence.save_obj(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
2023-10-31 12:57:30     _emit_insert_statements(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
2023-10-31 12:57:30     result = connection._execute_20(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
2023-10-31 12:57:30     return meth(self, args_10style, kwargs_10style, execution_options)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
2023-10-31 12:57:30     return connection._execute_clauseelement(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
2023-10-31 12:57:30     ret = self._execute_context(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
2023-10-31 12:57:30     self._handle_dbapi_exception(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
2023-10-31 12:57:30     util.raise_(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
2023-10-31 12:57:30     raise exception
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
2023-10-31 12:57:30     self.dialect.do_execute(
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2023-10-31 12:57:30     cursor.execute(statement, parameters)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 163, in execute
2023-10-31 12:57:30     result = self._query(query)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 321, in _query
2023-10-31 12:57:30     conn.query(q)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 505, in query
2023-10-31 12:57:30     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 724, in _read_query_result
2023-10-31 12:57:30     result.read()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1069, in read
2023-10-31 12:57:30     first_packet = self.connection._read_packet()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 676, in _read_packet
2023-10-31 12:57:30     packet.raise_for_error()
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 223, in raise_for_error
2023-10-31 12:57:30     err.raise_mysql_exception(self._data)
2023-10-31 12:57:30   File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
2023-10-31 12:57:30     raise errorclass(errno, errval)
2023-10-31 12:57:30 sqlalchemy.exc.DataError: (pymysql.err.DataError) (1406, "Data too long for column 'value' at row 1")
2023-10-31 12:57:30 [SQL: INSERT INTO config (value, `key`, comment) VALUES (%(value)s, %(key)s, %(comment)s)]
2023-10-31 12:57:30 [parameters: {'value': '  unstructured_api_url: ""  # 毕昇非结构化数据解析服务地址，提供包括OCR文字识别、表格识别、版式分析等能力。非必填，填写后能够提升PDF、图片、\n  embeddings: # 配置知识库的embedding服务，以下示例填写了两类embedding服务的配置方法 ... (875 characters truncated) ...  # 如果要支持溯源功能，由于溯源会展示源文件，必须配置 oss 存储\n    MINIO_ENDPOINT: ""\n    MINIO_SHAREPOIN: ""\n    MINIO_ACCESS_KEY: ""\n    MINIO_SECRET_KEY: ""\n\n# 全局配置大模型', 'key': 'knowledges', 'comment': None}]
2023-10-31 12:57:30 (Background on this error at: https://sqlalche.me/e/14/9h9h)
2023-10-31 12:57:30 
2023-10-31 12:57:30 ERROR:    Application startup failed. Exiting.
2023-10-31 12:57:30 ERROR:    Application startup failed. Exiting.

</p>
</details> 

修改数据库字段长度后可正常运行
![image](https://github.com/dataelement/bisheng/assets/918617/d83edefc-bd4f-47e2-bab7-36c976fd35a0)

**Comment by Minamiyama** [comment]
通过修改初始化部分代码并自己build后docker compose全新启动可解决新装问题
![fd2b2ce0c2e49cd79f7853739229482](https://github.com/dataelement/bisheng/assets/918617/8c5fe804-706b-49d5-a83b-85117a363b78)

**Comment by yaojin3616** [comment]
收到，在0.1.9 里更新
