### ISSUE TITLE
Flow 编译不通过, Error building node ProxyChatLLM: Authentication required.

### ISSUE THREAD

**Issue by xxch** [dataelement/bisheng#203]
`ERROR    [15:54:07] - ERROR - Error building node ProxyChatLLM: Authentication required.                                                                                                                      flows.py:134
                    Traceback (most recent call last):
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\bisheng\graph\vertex\base.py", line 267, in _get_and_instantiate_class
                        result = loading.instantiate_class(
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\bisheng\interface\initialize\loading.py", line 50, in instantiate_class
                        return instantiate_based_on_type(class_object, base_type, node_type,
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\bisheng\interface\initialize\loading.py", line 103, in instantiate_based_on_type
                        return instantiate_llm(node_type, class_object, params)
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\bisheng\interface\initialize\loading.py", line 202, in instantiate_llm
                        llm_config = settings.get_from_db('llm_request')
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\bisheng\settings.py", line 125, in get_from_db
                        cache = redis_client.get(redis_key)
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\bisheng\cache\redis.py", line 44, in get
                        return self.connection.get(key)
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\redis\commands\core.py", line 1829, in get
                        return self.execute_command("GET", name)
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\redis\client.py", line 533, in execute_command
                        conn = self.connection or pool.get_connection(command_name, **options)
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\redis\connection.py", line 1086, in get_connection
                        connection.connect()
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\redis\connection.py", line 276, in connect
                        self.on_connect()
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\redis\connection.py", line 379, in on_connect
                        self.read_response()
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\redis\connection.py", line 500, in read_response
                        response = self._parser.read_response(disable_decoding=disable_decoding)
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\redis\_parsers\resp2.py", line 15, in read_response
                        result = self._read_response(disable_decoding=disable_decoding)
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\redis\_parsers\resp2.py", line 38, in _read_response
                        raise error
                    redis.exceptions.AuthenticationError: Authentication required.
           
                    The above exception was the direct cause of the following exception:
           
                    Traceback (most recent call last):
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\bisheng\api\v1\flows.py", line 129, in update_flow
                        build_flow_no_yield(graph_data=db_flow.data,
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\bisheng\api\utils.py", line 210, in build_flow_no_yield
                        raise exc
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\bisheng\api\utils.py", line 200, in build_flow_no_yield
                        vertex.build()
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\bisheng\graph\vertex\types.py", line 58, in build
                        self._build()
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\bisheng\graph\vertex\base.py", line 155, in _build
                        self._get_and_instantiate_class()
                      File "C:\Users\zyl\.conda\envs\bisheng\lib\site-packages\bisheng\graph\vertex\base.py", line 275, in _get_and_instantiate_class
                        raise ValueError(f'Error building node {self.vertex_type}: {str(exc)}') from exc
                    ValueError: Error building node ProxyChatLLM: Authentication required.
           ERROR    [15:54:07] - ERROR - {'status_code': 500, 'status_message': 'Flow 编译不通过, Error building node ProxyChatLLM: Authentication required.'}                                                             main.py:19
?[32mINFO?[0m:     127.0.0.1:62670 - "?[1mPATCH /api/v1/flows/d60fdcfd-5198-4691-ba30-ecc952df1ddc HTTP/1.1?[0m" ?[32m200 OK?[0m
[15:54:15] DEBUG    [15:54:15] - DEBUG - Building ProxyChatLLM                                                                                                                                                            base.py:151
           DEBUG    [15:54:15] - DEBUG - Building ProxyChatLLM                                                                                                                                                            base.py:151
           ERROR    [15:54:15] - ERROR - Error building node ProxyChatLLM: Authentication required.    `
这个是缺少什么包吗

**Comment by xxch** [comment]
{'status_code': 500, 'status_message': 'Flow 编译不通过, Error building node ChatOpenAI: Authentication required.'}

**Comment by xxch** [comment]
问题解决了。这个问题是因为redis设置了密码。bisheng目前还不支持redis设置密码。导致在保存flow组件的时候无法保存到redis。在开启使用组件时获取不到而报错的
